# Generated by Django 4.2.9 on 2026-05-20 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='e.g. MH12AB1234', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid registration number (e.g. MH12AB1234)', regex='^[A-Z]{2}[\\s-]?[0-9]{2}[\\s-]?[A-Z]{1,2}[\\s-]?[0-9]{1,4}$')])),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('moped', 'Moped')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('cng', 'CNG')], max_length=20)),
                ('engine_number', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_registration',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('violation_type', models.CharField(choices=[('overspeeding', 'Over Speeding'), ('signal_jump', 'Signal Jump'), ('no_helmet', 'Riding Without Helmet'), ('wrong_side', 'Driving on Wrong Side'), ('drunk_driving', 'Drunk Driving'), ('no_insurance', 'No Insurance'), ('no_rc', 'No Registration Certificate'), ('no_license', 'Driving Without License'), ('mobile_use', 'Using Mobile While Driving'), ('triple_riding', 'Triple Riding'), ('other', 'Other')], max_length=50)),
                ('violation_date', models.DateField()),
                ('violation_location', models.CharField(max_length=200)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_challans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_challan',
                'ordering': ['-created_at'],
            },
        ),
    ]
